"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";

import { AulaLayout } from "@/components/AulaLayout";
import { StudentLayout } from "@/components/StudentLayout";
import { ResearchDocEditor } from "@/components/research/ResearchDocEditor";
import { studentHasResearchTokens } from "@/components/StudentTokenQuota";
import { IconFileText, IconRefresh, IconTrash } from "@/components/ui/ButtonIcon";
import { useAuth } from "@/hooks/useAuth";
import { fetchResearchOutlineFromApi } from "@/lib/research-api";
import { getDisciplineLabel } from "@/lib/research-disciplines";
import { researchGeneratePagePath } from "@/lib/research-generate-routes";
import {
	htmlToOutlineText,
	ideaToEditableDocument,
	markdownToDocHtml,
} from "@/lib/research-ideas";
import { peekOutlinePageContext, resolveOutlinePageContext, stageOutlinePageContext } from "@/lib/research-outline-context";
import { loadSavedOutline, removeSavedOutline, saveResearchOutline } from "@/lib/research-outline-storage";

type Props = {
	variant?: "lecturer" | "student";
};

function isLocalOutlineDraft(outline: string | null | undefined): boolean {
	if (!outline?.trim()) return true;
	return /<!--\s*aula-outline:local\s*-->/i.test(outline) || /\*\*Study focus points:\*\*/i.test(outline);
}

function seedOutlineFromIdea(context: NonNullable<ReturnType<typeof resolveOutlinePageContext>>): string | null {
	const saved = loadSavedOutline(context.idea, context.discipline, context.topic, context.scope)?.trim() ?? "";
	const looksAcademic = /(?:^|\n)#+\s*1\.\s*Introduction\b|(?:\*\*)1\.\s*Introduction(?:\*\*)/i.test(saved);
	const looksLegacyInformal =
		Boolean(saved) &&
		/(?:^|\n)#+\s*Why it matters\b|(?:^|\n)#+\s*Suggested approach\b|(?:^|\n)#+\s*Outline\b/i.test(saved) &&
		!looksAcademic;

	if (saved && looksAcademic && !isLocalOutlineDraft(saved)) return saved;
	if (saved && !looksLegacyInformal && !looksAcademic && !isLocalOutlineDraft(saved)) return saved;

	const academic = ideaToEditableDocument(
		context.idea,
		context.topic,
		context.discipline,
		context.scope,
	);
	saveResearchOutline({
		idea: context.idea,
		discipline: context.discipline,
		topic: context.topic,
		scope: context.scope,
		outline: academic,
	});
	return academic;
}

function ResearchOutlineContent({ variant = "lecturer" }: Props) {
	const searchParams = useSearchParams();
	const router = useRouter();
	const { user, setTokenQuota } = useAuth();
	const key = searchParams.get("key")?.trim() ?? "";
	const isStudent = variant === "student";
	const hasTokens = studentHasResearchTokens(user?.tokenQuota, user?.role);

	const [context, setContext] = useState(() => (key ? resolveOutlinePageContext(key) : null));
	const [outline, setOutline] = useState<string | null>(() => (key && context ? seedOutlineFromIdea(context) : null));
	const [editorHtml, setEditorHtml] = useState(() =>
		key && context ? markdownToDocHtml(seedOutlineFromIdea(context) ?? "") : "",
	);
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const saveTimerRef = useRef<number | null>(null);
	const autoGeneratedRef = useRef(false);

	const researchPath = isStudent ? "/student/research" : "/research";
	const backHref = context?.returnTo?.trim() || researchPath;

	useEffect(() => {
		if (!key) return;
		autoGeneratedRef.current = false;
		const resolved = resolveOutlinePageContext(key) ?? peekOutlinePageContext(key);
		setContext(resolved);
		if (resolved) {
			const seeded = seedOutlineFromIdea(resolved);
			setOutline(seeded);
			setEditorHtml(markdownToDocHtml(seeded ?? ""));
		}
	}, [key]);

	const persistOutline = useCallback(
		(nextOutline: string) => {
			if (!context || !nextOutline.trim()) return;
			saveResearchOutline({
				idea: context.idea,
				discipline: context.discipline,
				topic: context.topic,
				scope: context.scope,
				outline: nextOutline.trim(),
			});
			setOutline(nextOutline.trim());
		},
		[context],
	);

	const fromResearchNote = Boolean(context?.sources?.projectIds?.length);

	const generateOutline = useCallback(async () => {
		if (!context) return null;
		// Research note selected → never call outline generation.
		if (context.sources?.projectIds?.length) return null;
		if (!hasTokens) {
			const message = "You have used all your research tokens. Contact your instructor for more.";
			setError(message);
			return null;
		}
		setLoading(true);
		setError(null);
		try {
			const disciplineLabel = getDisciplineLabel(context.discipline);
			const { outline: outlineFromApi, tokenQuota } = await fetchResearchOutlineFromApi({
				idea: context.idea,
				disciplineLabel,
				topic: context.topic,
				scope: context.scope,
				sources: context.sources,
			});
			if (tokenQuota) setTokenQuota(tokenQuota);
			persistOutline(outlineFromApi);
			setEditorHtml(markdownToDocHtml(outlineFromApi));
			return outlineFromApi;
		} catch (err) {
			const message = err instanceof Error ? err.message : "Could not generate outline.";
			const cached = loadSavedOutline(context.idea, context.discipline, context.topic, context.scope);
			setOutline(cached);
			if (cached) setEditorHtml(markdownToDocHtml(cached));
			setError(message);
			return cached;
		} finally {
			setLoading(false);
		}
	}, [context, hasTokens, setTokenQuota, persistOutline]);

	useEffect(() => {
		if (!context || loading || !hasTokens || autoGeneratedRef.current) return;
		if (context.sources?.projectIds?.length) {
			autoGeneratedRef.current = true;
			return;
		}
		if (!isLocalOutlineDraft(outline)) return;
		autoGeneratedRef.current = true;
		void generateOutline();
	}, [context, outline, loading, hasTokens, generateOutline]);

	const handleEditorChange = useCallback(
		(html: string) => {
			setEditorHtml(html);
			const text = htmlToOutlineText(html);
			if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
			saveTimerRef.current = window.setTimeout(() => {
				persistOutline(text);
			}, 400);
		},
		[persistOutline],
	);

	useEffect(() => {
		return () => {
			if (saveTimerRef.current) window.clearTimeout(saveTimerRef.current);
		};
	}, []);

	const handleRemove = useCallback(() => {
		if (!context) return;
		removeSavedOutline(context.idea, context.discipline, context.topic, context.scope);
		router.push(backHref);
	}, [context, router, backHref]);

	const openGeneratePage = useCallback(() => {
		if (!context || !outline || !hasTokens) return;
		const outlineReturnTo =
			typeof window !== "undefined"
				? `${window.location.pathname}${window.location.search}`
				: undefined;
		stageOutlinePageContext({
			idea: context.idea,
			discipline: context.discipline,
			topic: context.topic,
			scope: context.scope,
			sources: context.sources,
			returnTo: outlineReturnTo,
		});
		router.push(researchGeneratePagePath(key, isStudent ? "student" : "lecturer"));
	}, [context, outline, hasTokens, key, router, isStudent]);

	const btnPrimaryClass = isStudent
		? "stu-paper-btn stu-paper-btn-primary research-outline-generate-btn"
		: "saved-research-btn saved-research-btn-primary research-outline-generate-btn";

	const btnClass = isStudent ? "stu-paper-btn" : "saved-research-btn";
	const canGenerate = Boolean(outline?.trim()) && hasTokens;

	if (!key || !context) {
		return (
			<div className={`research-outline-page${isStudent ? " research-outline-page-student" : ""}`}>
				<Link href={researchPath} className={isStudent ? "stu-research-paper-back" : "saved-research-back"}>
					← Back to research
				</Link>
				<div className="saved-research-empty">
					<h2>Research outline not found</h2>
					<p>Open an outline from a research idea card to view it here.</p>
				</div>
			</div>
		);
	}

	return (
		<div className={`research-outline-page${isStudent ? " research-outline-page-student" : ""}`}>
			<div className="saved-research-top">
				<Link href={backHref} className={isStudent ? "stu-research-paper-back" : "saved-research-back"}>
					← Back
				</Link>
			</div>

			<header className="research-outline-page-head">
				<div>
					<p className="research-outline-page-eyebrow">Academic research outline</p>
					<h1 className="research-outline-page-title">{context.idea.title}</h1>
					<p className="research-outline-page-meta">
						{getDisciplineLabel(context.discipline)} · {context.topic}
					</p>
				</div>
			</header>

			<div className="research-outline-page-toolbar">
				<button
					type="button"
					className={btnPrimaryClass}
					onClick={openGeneratePage}
					disabled={!canGenerate}
					title={
						!outline?.trim()
							? "Document is still preparing"
							: !hasTokens
								? "Research token limit reached"
								: undefined
					}
				>
					<IconFileText size={14} />
					Generate Research
				</button>
				{outline && !loading ? (
					<div className="research-outline-page-actions">
						{!fromResearchNote ? (
							<button type="button" className={`${btnClass} research-outline-regen`} onClick={() => void generateOutline()}>
								<IconRefresh size={14} />
								Regenerate outline
							</button>
						) : null}
						<button type="button" className={`${btnClass} research-outline-remove`} onClick={handleRemove}>
							<IconTrash size={14} />
							Remove
						</button>
					</div>
				) : null}
			</div>

			<div className="research-outline-page-body research-outline-page-body-doc">
				{loading && !outline ? (
					<div className="research-outline-loading" role="status">
						<span className="research-outline-spinner" aria-hidden />
						Searching literature and drafting a full academic outline…
					</div>
				) : null}

				{error && !outline ? (
					<div className="research-outline-error" role="alert">
						<p>{error}</p>
						<p className="research-outline-error-hint">
							Make sure the backend is running with the latest code (`npm run dev:backend` or restart `npm start`).
						</p>
					</div>
				) : null}

				{error && outline ? (
					<div className="research-outline-error" role="alert">
						<p>{error}</p>
					</div>
				) : null}

				{outline || editorHtml ? (
					<ResearchDocEditor
						value={editorHtml}
						placeholder="Edit this research idea document — outline, research questions, and notes…"
						ariaLabel="Editable research idea document"
						minHeight="32rem"
						onChange={handleEditorChange}
						onBlur={() => persistOutline(htmlToOutlineText(editorHtml))}
					/>
				) : null}
			</div>
		</div>
	);
}

export function ResearchOutlinePage({ variant = "lecturer" }: Props) {
	const page = <ResearchOutlineContent variant={variant} />;

	if (variant === "student") {
		return <StudentLayout>{page}</StudentLayout>;
	}

	return <AulaLayout showRightPanel={false}>{page}</AulaLayout>;
}
