import { apiUrl } from "@/lib/api";
import type {
	AdminBackupFile,
	AdminBackupTable,
	AdminLectureRecord,
	AdminTokenRecord,
	LectureAdminStats,
	TokenAdminStats,
	UpdateTokenInput,
} from "@/lib/admin";
import type {
	AiContributionStatementRecord,
	AiSystemRecord,
	AiSystemStats,
	AlertStats,
	ApprovalRequestRecord,
	ApprovalStats,
	AuditAlertStats,
	AuditLogRecord,
	ComplianceControlRecord,
	ComplianceStats,
	ContributionStats,
	DeletionRequestRecord,
	GovernanceAlertRecord,
	GovernanceDashboard,
	GovernanceIncidentRecord,
	GovernancePolicyRecord,
	GovernanceReportAudience,
	GovernanceReportRecord,
	GovernanceRiskRecord,
	IncidentStats,
	PolicyEvaluation,
	PolicyStats,
	PrivacyStats,
	ProvenanceStats,
	ResearchPrivacySettingRecord,
	ResearchProvenanceRecord,
	RetentionPolicyRecord,
	RetentionStats,
	RiskStats,
	UsageAnalytics,
} from "@/lib/admin-governance";
import type {
	CreateUserInput,
	DashboardStats,
	RecentSessionTopic,
	SessionSummary,
	UpdateUserInput,
	UserRecord,
} from "@/lib/dashboard";
import { authHeaders } from "@/lib/auth";

async function adminJson<T>(path: string, init?: RequestInit): Promise<T> {
	const res = await fetch(apiUrl(path), {
		...init,
		headers: { ...authHeaders(), ...init?.headers },
	});
	const data = (await res.json()) as T & { error?: string; message?: string };
	if (!res.ok) {
		const msg = data.message || data.error || "Request failed.";
		// Fastify's generic 404 uses error:"Not Found"; prefer message when present.
		throw new Error(
			data.error === "Not Found" && data.message ? data.message : data.error ?? msg,
		);
	}
	return data;
}

export async function fetchAdminStats(): Promise<DashboardStats> {
	const data = await adminJson<{ stats: DashboardStats }>("/api/admin/stats");
	return data.stats;
}

export async function fetchAdminRecentSessionTopics(limit = 8): Promise<RecentSessionTopic[]> {
	const data = await adminJson<{ sessions: RecentSessionTopic[] }>(
		`/api/admin/sessions/recent-topics?limit=${limit}`,
	);
	return data.sessions;
}

export async function fetchAdminSession(id: string): Promise<RecentSessionTopic> {
	const data = await adminJson<{ session: RecentSessionTopic }>(`/api/admin/sessions/${id}`);
	return data.session;
}

export async function stopAdminSession(id: string): Promise<RecentSessionTopic> {
	const data = await adminJson<{ session: RecentSessionTopic }>(`/api/admin/sessions/${id}/stop`, {
		method: "POST",
	});
	return data.session;
}

export async function deleteAdminSession(id: string): Promise<void> {
	await adminJson(`/api/admin/sessions/${id}`, { method: "DELETE" });
}

export function exportSessionTopicsCsv(sessions: RecentSessionTopic[]): void {
	const headers = [
		"Topic",
		"Lecture",
		"Generated by",
		"Email",
		"Workflow",
		"Model",
		"State",
		"Messages",
		"Created",
		"Updated",
	];
	const rows = sessions.map((session) => [
		session.topic,
		session.lectureTitle ?? "",
		session.generatedByName ?? "",
		session.generatedByEmail ?? "",
		session.workflow ?? "",
		session.model,
		session.state,
		String(session.messageCount),
		session.createdAt,
		session.updatedAt,
	]);
	const csv = [headers, ...rows]
		.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
		.join("\n");
	const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = `aula-sessions-${new Date().toISOString().slice(0, 10)}.csv`;
	link.click();
	URL.revokeObjectURL(url);
}

export async function fetchAdminSessions(limit = 50): Promise<SessionSummary[]> {
	const data = await adminJson<{ sessions: SessionSummary[] }>(`/api/admin/sessions?limit=${limit}`);
	return data.sessions;
}

export async function fetchAdminUsers(): Promise<UserRecord[]> {
	const data = await adminJson<{ users: UserRecord[] }>("/api/admin/users");
	return data.users;
}

export async function fetchAdminUser(id: string): Promise<UserRecord> {
	const data = await adminJson<{ user: UserRecord }>(`/api/admin/users/${encodeURIComponent(id)}`);
	return data.user;
}

export async function fetchAdminConsoleAdmins(): Promise<UserRecord[]> {
	const data = await adminJson<{ users: UserRecord[] }>("/api/admin/admins");
	return data.users;
}

export type UniversityRecord = {
	id: string;
	catalogueId: string;
	name: string;
	slug: string;
	country?: string;
	status: "active" | "inactive";
	userCount: number;
	adminCount: number;
	defaultStudentTokens?: number | null;
	defaultLecturerTokens?: number | null;
	onboardedAt: string | null;
	createdAt: string;
	updatedAt: string;
};

export type UniversityDetailRecord = UniversityRecord & {
	studentCount: number;
	lecturerCount: number;
};

export async function fetchAdminUniversities(): Promise<UniversityRecord[]> {
	const data = await adminJson<{ universities: UniversityRecord[] }>("/api/admin/universities");
	return data.universities;
}

export async function fetchAdminUniversity(idOrSlug: string): Promise<UniversityDetailRecord> {
	const key = idOrSlug.trim();
	try {
		const data = await adminJson<{ university: UniversityDetailRecord }>(
			`/api/admin/universities/${encodeURIComponent(key)}`,
		);
		return data.university;
	} catch (primaryError) {
		// Fallback when detail route is unavailable (stale backend) or lookup key is a slug.
		const universities = await fetchAdminUniversities();
		const match = universities.find(
			(u) => u.id === key || u.slug === key || u.catalogueId === key,
		);
		if (!match) {
			throw primaryError instanceof Error
				? primaryError
				: new Error("University not found.");
		}
		return {
			...match,
			studentCount: 0,
			lecturerCount: 0,
		};
	}
}

export async function onboardAdminUniversity(input: {
	catalogueId: string;
	name: string;
	country?: string;
	status?: "active" | "inactive";
}): Promise<UniversityRecord> {
	const data = await adminJson<{ university: UniversityRecord }>("/api/admin/universities", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ country: "NG", ...input }),
	});
	return data.university;
}

export type BulkOnboardResult = {
	created: number;
	updated: number;
	failed: number;
	total: number;
	errors: Array<{ catalogueId: string; error: string }>;
};

export async function onboardAdminUniversitiesBulk(input: {
	country?: string;
	status?: "active" | "inactive";
	universities: Array<{ catalogueId: string; name: string }>;
}): Promise<BulkOnboardResult> {
	const data = await adminJson<{ result: BulkOnboardResult }>("/api/admin/universities/bulk", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ country: "NG", status: "active", ...input }),
	});
	return data.result;
}

export async function updateAdminUniversity(
	id: string,
	input: Partial<{
		name: string;
		status: "active" | "inactive";
		defaultStudentTokens: number | null;
		defaultLecturerTokens: number | null;
	}>,
): Promise<UniversityRecord> {
	const data = await adminJson<{ university: UniversityRecord }>(
		`/api/admin/universities/${encodeURIComponent(id)}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.university;
}

export async function deleteAdminUniversity(
	id: string,
	confirmName: string,
): Promise<{
	university: UniversityRecord | null;
	hardDeleted: boolean;
	suspendedUsers: number;
}> {
	const data = await adminJson<{
		university: UniversityRecord | null;
		hardDeleted: boolean;
		suspendedUsers: number;
	}>(`/api/admin/universities/${encodeURIComponent(id)}/offboard`, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ confirmName }),
	});
	return data;
}

export async function createAdminUser(input: CreateUserInput & { password?: string }): Promise<UserRecord> {
	const data = await adminJson<{ user: UserRecord }>("/api/admin/users", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.user;
}

export async function updateAdminUser(id: string, input: UpdateUserInput): Promise<UserRecord> {
	const data = await adminJson<{ user: UserRecord }>(`/api/admin/users/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.user;
}

export async function deleteAdminUser(id: string): Promise<void> {
	await adminJson(`/api/admin/users/${id}`, { method: "DELETE" });
}

export async function resetAdminUserPassword(id: string, password: string): Promise<void> {
	await adminJson(`/api/admin/users/${id}/reset-password`, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ password }),
	});
}

export async function bulkAdminUserStatus(
	ids: string[],
	status: "active" | "inactive" | "suspended",
	suspensionReason?: string,
): Promise<number> {
	const data = await adminJson<{ updated: number }>("/api/admin/users/bulk-status", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids, status, suspensionReason }),
	});
	return data.updated;
}

export async function bulkAdminDeleteUsers(ids: string[]): Promise<number> {
	const data = await adminJson<{ deleted: number }>("/api/admin/users/bulk-delete", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids }),
	});
	return data.deleted;
}

export async function fetchAdminLectures(): Promise<{
	lectures: AdminLectureRecord[];
	stats: LectureAdminStats;
}> {
	const data = await adminJson<{
		lectures: AdminLectureRecord[];
		stats: LectureAdminStats;
	}>("/api/admin/lectures");
	return { lectures: data.lectures ?? [], stats: data.stats! };
}

export async function deleteAdminLecture(id: string): Promise<void> {
	await adminJson(`/api/admin/lectures/${id}`, { method: "DELETE" });
}

export async function fetchAdminTokens(): Promise<{
	users: AdminTokenRecord[];
	stats: TokenAdminStats;
}> {
	const data = await adminJson<{
		users: AdminTokenRecord[];
		stats: TokenAdminStats;
	}>("/api/admin/tokens");
	return { users: data.users ?? [], stats: data.stats! };
}

export async function updateAdminTokens(
	userId: string,
	input: UpdateTokenInput,
): Promise<AdminTokenRecord> {
	const data = await adminJson<{ user: AdminTokenRecord }>(`/api/admin/tokens/${userId}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.user!;
}

export async function bulkAdminResetTokens(ids: string[]): Promise<number> {
	const data = await adminJson<{ reset: number }>("/api/admin/tokens/bulk-reset", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids }),
	});
	return data.reset;
}

export async function fetchAdminBackupTables(): Promise<AdminBackupTable[]> {
	const data = await adminJson<{ tables: AdminBackupTable[] }>("/api/admin/backup/tables");
	return data.tables ?? [];
}

export async function fetchAdminBackupFiles(): Promise<AdminBackupFile[]> {
	const data = await adminJson<{ files: AdminBackupFile[] }>("/api/admin/backup/files");
	return data.files ?? [];
}

export async function createAdminBackup(): Promise<AdminBackupFile> {
	const data = await adminJson<{ file: AdminBackupFile }>("/api/admin/backup", { method: "POST" });
	return data.file;
}

export async function downloadAdminBackupFile(filename: string): Promise<void> {
	const res = await fetch(apiUrl(`/api/admin/backup/files/${encodeURIComponent(filename)}`), {
		headers: authHeaders(),
	});
	if (!res.ok) {
		const data = (await res.json()) as { error?: string };
		throw new Error(data.error ?? "Download failed.");
	}
	const blob = await res.blob();
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = filename;
	link.click();
	URL.revokeObjectURL(url);
}

export function exportUsersCsv(users: UserRecord[]): void {
	const headers = [
		"Name",
		"Email",
		"Role",
		"Status",
		"Faculty",
		"Department",
		"Programme",
		"Cohort",
		"Institution",
		"Last Active",
		"Joined",
	];
	const rows = users.map((user) => [
		user.name,
		user.email,
		user.role,
		user.status,
		user.faculty ?? "",
		user.department ?? "",
		user.programme ?? "",
		user.cohort ?? "",
		user.institution ?? "",
		user.lastActiveAt ?? "",
		user.createdAt,
	]);
	const csv = [headers, ...rows]
		.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
		.join("\n");
	const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = `aula-users-${new Date().toISOString().slice(0, 10)}.csv`;
	link.click();
	URL.revokeObjectURL(url);
}

/* ── Governance APIs ─────────────────────────────────────────────────── */

export async function fetchGovernanceDashboard(): Promise<GovernanceDashboard> {
	const data = await adminJson<{ dashboard: GovernanceDashboard }>("/api/admin/governance");
	return data.dashboard;
}

export async function fetchUsageAnalytics(): Promise<UsageAnalytics> {
	const data = await adminJson<{ analytics: UsageAnalytics }>("/api/admin/analytics");
	return data.analytics;
}

export async function fetchAdminAnalytics(): Promise<UsageAnalytics> {
	return fetchUsageAnalytics();
}

export async function fetchAdminOverview() {
	const data = await adminJson<{ overview: import("@/lib/admin-governance").PlatformOverview }>(
		"/api/admin/overview",
	);
	return data.overview;
}

export async function fetchAdminPolicies(): Promise<{
	policies: GovernancePolicyRecord[];
	stats: PolicyStats;
}> {
	const data = await adminJson<{ policies: GovernancePolicyRecord[]; stats: PolicyStats }>(
		"/api/admin/policies",
	);
	return { policies: data.policies ?? [], stats: data.stats! };
}

export async function createAdminPolicy(input: {
	name: string;
	description?: string;
	scope: string;
	target: string;
	effect: string;
	roles?: string[];
	faculties?: string[];
	enabled?: boolean;
	priority?: number;
}): Promise<GovernancePolicyRecord> {
	const data = await adminJson<{ policy: GovernancePolicyRecord }>("/api/admin/policies", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.policy;
}

export async function updateAdminPolicy(
	id: string,
	input: Partial<{
		name: string;
		description: string;
		scope: string;
		target: string;
		effect: string;
		roles: string[];
		faculties: string[];
		enabled: boolean;
		priority: number;
	}>,
): Promise<GovernancePolicyRecord> {
	const data = await adminJson<{ policy: GovernancePolicyRecord }>(`/api/admin/policies/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.policy;
}

export async function deleteAdminPolicy(id: string): Promise<void> {
	await adminJson(`/api/admin/policies/${id}`, { method: "DELETE" });
}

export async function evaluateAdminPolicy(input: {
	scope: string;
	target: string;
	role: string;
	faculty?: string;
}): Promise<PolicyEvaluation> {
	const data = await adminJson<{ result: PolicyEvaluation }>("/api/admin/policies/evaluate", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.result;
}

export async function fetchAdminAuditLogs(params?: {
	limit?: number;
	flagged?: boolean;
	category?: string;
	severity?: string;
	q?: string;
}): Promise<{ logs: AuditLogRecord[]; stats: AuditAlertStats }> {
	const qs = new URLSearchParams();
	if (params?.limit) qs.set("limit", String(params.limit));
	if (params?.flagged) qs.set("flagged", "1");
	if (params?.category) qs.set("category", params.category);
	if (params?.severity) qs.set("severity", params.severity);
	if (params?.q) qs.set("q", params.q);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ logs: AuditLogRecord[]; stats: AuditAlertStats }>(
		`/api/admin/audit${suffix}`,
	);
	return { logs: data.logs ?? [], stats: data.stats! };
}

export async function flagAdminAuditLog(
	id: string,
	reason: string,
	severity?: string,
): Promise<AuditLogRecord> {
	const data = await adminJson<{ log: AuditLogRecord }>(`/api/admin/audit/${id}/flag`, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ reason, severity }),
	});
	return data.log;
}

export async function fetchAdminApprovals(params?: {
	status?: string;
	kind?: string;
}): Promise<{ approvals: ApprovalRequestRecord[]; stats: ApprovalStats }> {
	const qs = new URLSearchParams();
	if (params?.status) qs.set("status", params.status);
	if (params?.kind) qs.set("kind", params.kind);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ approvals: ApprovalRequestRecord[]; stats: ApprovalStats }>(
		`/api/admin/approvals${suffix}`,
	);
	return { approvals: data.approvals ?? [], stats: data.stats! };
}

export async function createAdminApproval(input: {
	title: string;
	description?: string;
	kind: string;
	justification?: string;
	riskNotes?: string;
}): Promise<ApprovalRequestRecord> {
	const data = await adminJson<{ approval: ApprovalRequestRecord }>("/api/admin/approvals", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.approval;
}

export async function reviewAdminApproval(
	id: string,
	input: { status: string; reviewNotes?: string },
): Promise<ApprovalRequestRecord> {
	const data = await adminJson<{ approval: ApprovalRequestRecord }>(`/api/admin/approvals/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.approval;
}

export async function fetchAdminReports(): Promise<GovernanceReportRecord[]> {
	const data = await adminJson<{ reports: GovernanceReportRecord[] }>("/api/admin/reports");
	return data.reports ?? [];
}

export async function fetchAdminReport(id: string): Promise<GovernanceReportRecord> {
	const data = await adminJson<{ report: GovernanceReportRecord }>(`/api/admin/reports/${id}`);
	return data.report;
}

export async function generateAdminReport(input: {
	audience?: GovernanceReportAudience;
	periodStart?: string;
	periodEnd?: string;
	reportType?: string;
	format?: string;
	faculty?: string;
	department?: string;
	programme?: string;
	userRole?: string;
}): Promise<GovernanceReportRecord> {
	const data = await adminJson<{ report: GovernanceReportRecord }>("/api/admin/reports/generate", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ audience: "both", ...input }),
	});
	return data.report;
}

export function exportGovernanceReportText(report: GovernanceReportRecord): void {
	const lines = [
		report.title,
		`Audience: ${report.audience}`,
		`Period: ${report.periodStart.slice(0, 10)} — ${report.periodEnd.slice(0, 10)}`,
		`Generated: ${report.createdAt}`,
		"",
		"SUMMARY",
		report.summary,
		"",
		...report.sections.flatMap((section) => [section.heading, section.body, ""]),
	];
	const blob = new Blob([lines.join("\n")], { type: "text/plain;charset=utf-8;" });
	const url = URL.createObjectURL(blob);
	const link = document.createElement("a");
	link.href = url;
	link.download = `governance-report-${report.audience}-${report.createdAt.slice(0, 10)}.txt`;
	link.click();
	URL.revokeObjectURL(url);
}

/* ── Risk / compliance / incidents / inventory ───────────────────────── */

export async function fetchAdminRisks(params?: {
	status?: string;
	category?: string;
}): Promise<{ risks: GovernanceRiskRecord[]; stats: RiskStats }> {
	const qs = new URLSearchParams();
	if (params?.status) qs.set("status", params.status);
	if (params?.category) qs.set("category", params.category);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ risks: GovernanceRiskRecord[]; stats: RiskStats }>(
		`/api/admin/risks${suffix}`,
	);
	return { risks: data.risks ?? [], stats: data.stats! };
}

export async function createAdminRisk(input: Record<string, unknown>): Promise<GovernanceRiskRecord> {
	const data = await adminJson<{ risk: GovernanceRiskRecord }>("/api/admin/risks", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.risk;
}

export async function updateAdminRisk(
	id: string,
	input: Record<string, unknown>,
): Promise<GovernanceRiskRecord> {
	const data = await adminJson<{ risk: GovernanceRiskRecord }>(`/api/admin/risks/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.risk;
}

export async function deleteAdminRisk(id: string): Promise<void> {
	await adminJson(`/api/admin/risks/${id}`, { method: "DELETE" });
}

export async function fetchAdminCompliance(params?: {
	framework?: string;
	status?: string;
}): Promise<{ controls: ComplianceControlRecord[]; stats: ComplianceStats }> {
	const qs = new URLSearchParams();
	if (params?.framework) qs.set("framework", params.framework);
	if (params?.status) qs.set("status", params.status);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ controls: ComplianceControlRecord[]; stats: ComplianceStats }>(
		`/api/admin/compliance${suffix}`,
	);
	return { controls: data.controls ?? [], stats: data.stats! };
}

export async function createAdminCompliance(
	input: Record<string, unknown>,
): Promise<ComplianceControlRecord> {
	const data = await adminJson<{ control: ComplianceControlRecord }>("/api/admin/compliance", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.control;
}

export async function updateAdminCompliance(
	id: string,
	input: Record<string, unknown>,
): Promise<ComplianceControlRecord> {
	const data = await adminJson<{ control: ComplianceControlRecord }>(`/api/admin/compliance/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.control;
}

export async function deleteAdminCompliance(id: string): Promise<void> {
	await adminJson(`/api/admin/compliance/${id}`, { method: "DELETE" });
}

export async function fetchAdminIncidents(params?: {
	status?: string;
	severity?: string;
}): Promise<{ incidents: GovernanceIncidentRecord[]; stats: IncidentStats }> {
	const qs = new URLSearchParams();
	if (params?.status) qs.set("status", params.status);
	if (params?.severity) qs.set("severity", params.severity);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ incidents: GovernanceIncidentRecord[]; stats: IncidentStats }>(
		`/api/admin/incidents${suffix}`,
	);
	return { incidents: data.incidents ?? [], stats: data.stats! };
}

export async function createAdminIncident(
	input: Record<string, unknown>,
): Promise<GovernanceIncidentRecord> {
	const data = await adminJson<{ incident: GovernanceIncidentRecord }>("/api/admin/incidents", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.incident;
}

export async function updateAdminIncident(
	id: string,
	input: Record<string, unknown>,
): Promise<GovernanceIncidentRecord> {
	const data = await adminJson<{ incident: GovernanceIncidentRecord }>(
		`/api/admin/incidents/${id}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.incident;
}

export async function fetchAdminInventory(params?: {
	status?: string;
	riskTier?: string;
}): Promise<{ systems: AiSystemRecord[]; stats: AiSystemStats }> {
	const qs = new URLSearchParams();
	if (params?.status) qs.set("status", params.status);
	if (params?.riskTier) qs.set("riskTier", params.riskTier);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ systems: AiSystemRecord[]; stats: AiSystemStats }>(
		`/api/admin/inventory${suffix}`,
	);
	return { systems: data.systems ?? [], stats: data.stats! };
}

export async function createAdminInventorySystem(
	input: Record<string, unknown>,
): Promise<AiSystemRecord> {
	const data = await adminJson<{ system: AiSystemRecord }>("/api/admin/inventory", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.system;
}

export async function updateAdminInventorySystem(
	id: string,
	input: Record<string, unknown>,
): Promise<AiSystemRecord> {
	const data = await adminJson<{ system: AiSystemRecord }>(`/api/admin/inventory/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.system;
}

export async function deleteAdminInventorySystem(id: string): Promise<void> {
	await adminJson(`/api/admin/inventory/${id}`, { method: "DELETE" });
}

/* ── Alerts / contributions / provenance / privacy / retention ───────── */

export async function fetchAdminAlerts(params?: {
	status?: string;
	severity?: string;
	kind?: string;
}): Promise<{ alerts: GovernanceAlertRecord[]; stats: AlertStats }> {
	const qs = new URLSearchParams();
	if (params?.status) qs.set("status", params.status);
	if (params?.severity) qs.set("severity", params.severity);
	if (params?.kind) qs.set("kind", params.kind);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ alerts: GovernanceAlertRecord[]; stats: AlertStats }>(
		`/api/admin/alerts${suffix}`,
	);
	return { alerts: data.alerts ?? [], stats: data.stats! };
}

export async function createAdminAlert(
	input: Record<string, unknown>,
): Promise<GovernanceAlertRecord> {
	const data = await adminJson<{ alert: GovernanceAlertRecord }>("/api/admin/alerts", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.alert;
}

export async function updateAdminAlert(
	id: string,
	input: Record<string, unknown>,
): Promise<GovernanceAlertRecord> {
	const data = await adminJson<{ alert: GovernanceAlertRecord }>(`/api/admin/alerts/${id}`, {
		method: "PATCH",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.alert;
}

export async function fetchAdminContributions(params?: {
	verified?: boolean;
	disclosureComplete?: boolean;
	outputType?: string;
}): Promise<{ statements: AiContributionStatementRecord[]; stats: ContributionStats }> {
	const qs = new URLSearchParams();
	if (params?.verified === true) qs.set("verified", "1");
	if (params?.verified === false) qs.set("verified", "0");
	if (params?.disclosureComplete === true) qs.set("disclosureComplete", "1");
	if (params?.disclosureComplete === false) qs.set("disclosureComplete", "0");
	if (params?.outputType) qs.set("outputType", params.outputType);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{
		statements: AiContributionStatementRecord[];
		stats: ContributionStats;
	}>(`/api/admin/contributions${suffix}`);
	return { statements: data.statements ?? [], stats: data.stats! };
}

export async function createAdminContribution(
	input: Record<string, unknown>,
): Promise<AiContributionStatementRecord> {
	const data = await adminJson<{ statement: AiContributionStatementRecord }>(
		"/api/admin/contributions",
		{
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.statement;
}

export async function updateAdminContribution(
	id: string,
	input: Record<string, unknown>,
): Promise<AiContributionStatementRecord> {
	const data = await adminJson<{ statement: AiContributionStatementRecord }>(
		`/api/admin/contributions/${id}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.statement;
}

export async function fetchAdminProvenance(params?: {
	status?: string;
	outputType?: string;
}): Promise<{ records: ResearchProvenanceRecord[]; stats: ProvenanceStats }> {
	const qs = new URLSearchParams();
	if (params?.status) qs.set("status", params.status);
	if (params?.outputType) qs.set("outputType", params.outputType);
	const suffix = qs.toString() ? `?${qs.toString()}` : "";
	const data = await adminJson<{ records: ResearchProvenanceRecord[]; stats: ProvenanceStats }>(
		`/api/admin/provenance${suffix}`,
	);
	return { records: data.records ?? [], stats: data.stats! };
}

export async function createAdminProvenance(
	input: Record<string, unknown>,
): Promise<ResearchProvenanceRecord> {
	const data = await adminJson<{ record: ResearchProvenanceRecord }>("/api/admin/provenance", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.record;
}

export async function updateAdminProvenance(
	id: string,
	input: Record<string, unknown>,
): Promise<ResearchProvenanceRecord> {
	const data = await adminJson<{ record: ResearchProvenanceRecord }>(
		`/api/admin/provenance/${id}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.record;
}

export async function fetchAdminPrivacy(): Promise<{
	settings: ResearchPrivacySettingRecord[];
	stats: PrivacyStats;
}> {
	const data = await adminJson<{ settings: ResearchPrivacySettingRecord[]; stats: PrivacyStats }>(
		"/api/admin/privacy",
	);
	return { settings: data.settings ?? [], stats: data.stats! };
}

export async function createAdminPrivacy(
	input: Record<string, unknown>,
): Promise<ResearchPrivacySettingRecord> {
	const data = await adminJson<{ setting: ResearchPrivacySettingRecord }>("/api/admin/privacy", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify(input),
	});
	return data.setting;
}

export async function updateAdminPrivacy(
	id: string,
	input: Record<string, unknown>,
): Promise<ResearchPrivacySettingRecord> {
	const data = await adminJson<{ setting: ResearchPrivacySettingRecord }>(
		`/api/admin/privacy/${id}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.setting;
}

export async function deleteAdminPrivacy(id: string): Promise<void> {
	await adminJson(`/api/admin/privacy/${id}`, { method: "DELETE" });
}

export async function fetchAdminRetention(): Promise<{
	policies: RetentionPolicyRecord[];
	deletionRequests: DeletionRequestRecord[];
	stats: RetentionStats;
}> {
	const data = await adminJson<{
		policies: RetentionPolicyRecord[];
		deletionRequests: DeletionRequestRecord[];
		stats: RetentionStats;
	}>("/api/admin/retention");
	return {
		policies: data.policies ?? [],
		deletionRequests: data.deletionRequests ?? [],
		stats: data.stats!,
	};
}

export async function createAdminRetentionPolicy(
	input: Record<string, unknown>,
): Promise<RetentionPolicyRecord> {
	const data = await adminJson<{ policy: RetentionPolicyRecord }>(
		"/api/admin/retention/policies",
		{
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.policy;
}

export async function updateAdminRetentionPolicy(
	id: string,
	input: Record<string, unknown>,
): Promise<RetentionPolicyRecord> {
	const data = await adminJson<{ policy: RetentionPolicyRecord }>(
		`/api/admin/retention/policies/${id}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.policy;
}

export async function deleteAdminRetentionPolicy(id: string): Promise<void> {
	await adminJson(`/api/admin/retention/policies/${id}`, { method: "DELETE" });
}

export async function createAdminDeletionRequest(
	input: Record<string, unknown>,
): Promise<DeletionRequestRecord> {
	const data = await adminJson<{ deletionRequest: DeletionRequestRecord }>(
		"/api/admin/retention/deletion-requests",
		{
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.deletionRequest;
}

export async function updateAdminDeletionRequest(
	id: string,
	input: Record<string, unknown>,
): Promise<DeletionRequestRecord> {
	const data = await adminJson<{ deletionRequest: DeletionRequestRecord }>(
		`/api/admin/retention/deletion-requests/${id}`,
		{
			method: "PATCH",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(input),
		},
	);
	return data.deletionRequest;
}

export type AdminResearchOwner = {
	id: string | null;
	name: string;
	email: string;
	role: string | null;
	universityId: string | null;
	institution: string | null;
};

export type AdminResearchStats = {
	papers: number;
	notebooks: number;
	documents: number;
	datasets: number;
	uploads: number;
	notebooksWithSync: number;
};

export type AdminResearchPaperRecord = {
	id: string;
	title: string;
	topic: string;
	workflow: string;
	humanEdited: boolean;
	contentLength: number;
	tokenUsage: number | null;
	owner: AdminResearchOwner;
	createdAt: string;
	updatedAt: string;
};

export type AdminResearchPaperDetail = AdminResearchPaperRecord & {
	content: string;
	aiBaselineContent: string | null;
	sources: {
		documentIds: string[];
		datasetIds: string[];
		noteIds: string[];
		projectIds: string[];
	};
};

export type AdminResearchNotebookRecord = {
	id: string;
	title: string;
	description: string;
	projectType: string;
	status: string;
	progress: number;
	favorite: boolean;
	hasNotebook: boolean;
	notebookBytes: number;
	pageCount: number;
	draftCount: number;
	sectionCount: number;
	documentCount: number;
	datasetCount: number;
	noteCount: number;
	owner: AdminResearchOwner;
	startedAt: string | null;
	createdAt: string;
	updatedAt: string;
};

export type AdminResearchNotebookDetail = AdminResearchNotebookRecord & {
	sections: Array<{ id: string; title: string; contentLength: number }>;
	notebookSummary: {
		pages: Array<{ id: string; title: string }>;
		drafts: Array<{ id: string; title: string }>;
		datasets: Array<{ id: string; title: string }>;
		references: number;
		assets: number;
	} | null;
};

export type AdminResearchUploadKind = "document" | "dataset";

export type AdminResearchUploadRecord = {
	id: string;
	kind: AdminResearchUploadKind;
	title: string;
	fileName: string;
	fileMime: string;
	sizeLabel: string;
	fileSizeBytes: number;
	hasFile: boolean;
	storage: "minio" | "mongo" | "none";
	projectId: string | null;
	projectTitle: string | null;
	visibility: string | null;
	format: string | null;
	owner: AdminResearchOwner;
	createdAt: string;
	updatedAt: string;
};

function researchQuery(params?: { universityId?: string; limit?: number; kind?: string }): string {
	const q = new URLSearchParams();
	if (params?.universityId) q.set("universityId", params.universityId);
	if (params?.limit) q.set("limit", String(params.limit));
	if (params?.kind) q.set("kind", params.kind);
	const s = q.toString();
	return s ? `?${s}` : "";
}

export async function fetchAdminResearchStats(universityId?: string): Promise<AdminResearchStats> {
	const data = await adminJson<{ stats: AdminResearchStats }>(
		`/api/admin/research/stats${researchQuery({ universityId })}`,
	);
	return data.stats;
}

export async function fetchAdminResearchPapers(params?: {
	universityId?: string;
	limit?: number;
}): Promise<AdminResearchPaperRecord[]> {
	const data = await adminJson<{ papers: AdminResearchPaperRecord[] }>(
		`/api/admin/research/papers${researchQuery(params)}`,
	);
	return data.papers ?? [];
}

export async function fetchAdminResearchPaper(id: string): Promise<AdminResearchPaperDetail> {
	const data = await adminJson<{ paper: AdminResearchPaperDetail }>(
		`/api/admin/research/papers/${id}`,
	);
	return data.paper;
}

export async function deleteAdminResearchPaper(id: string): Promise<void> {
	await adminJson(`/api/admin/research/papers/${id}`, { method: "DELETE" });
}

export async function bulkDeleteAdminResearchPapers(ids: string[]): Promise<number> {
	const data = await adminJson<{ deleted: number }>("/api/admin/research/papers/bulk-delete", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids }),
	});
	return data.deleted;
}

export async function fetchAdminResearchNotebooks(params?: {
	universityId?: string;
	limit?: number;
}): Promise<AdminResearchNotebookRecord[]> {
	const data = await adminJson<{ notebooks: AdminResearchNotebookRecord[] }>(
		`/api/admin/research/notebooks${researchQuery(params)}`,
	);
	return data.notebooks ?? [];
}

export async function fetchAdminResearchNotebook(id: string): Promise<AdminResearchNotebookDetail> {
	const data = await adminJson<{ notebook: AdminResearchNotebookDetail }>(
		`/api/admin/research/notebooks/${id}`,
	);
	return data.notebook;
}

export async function deleteAdminResearchNotebook(id: string): Promise<void> {
	await adminJson(`/api/admin/research/notebooks/${id}`, { method: "DELETE" });
}

export async function bulkDeleteAdminResearchNotebooks(ids: string[]): Promise<number> {
	const data = await adminJson<{ deleted: number }>("/api/admin/research/notebooks/bulk-delete", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ ids }),
	});
	return data.deleted;
}

export async function fetchAdminResearchUploads(params?: {
	universityId?: string;
	limit?: number;
	kind?: AdminResearchUploadKind | "all";
}): Promise<AdminResearchUploadRecord[]> {
	const data = await adminJson<{ uploads: AdminResearchUploadRecord[] }>(
		`/api/admin/research/uploads${researchQuery(params)}`,
	);
	return data.uploads ?? [];
}

export async function deleteAdminResearchUpload(
	kind: AdminResearchUploadKind,
	id: string,
): Promise<void> {
	await adminJson(`/api/admin/research/uploads/${kind}/${id}`, { method: "DELETE" });
}

export async function bulkDeleteAdminResearchUploads(
	items: Array<{ id: string; kind: AdminResearchUploadKind }>,
): Promise<number> {
	const data = await adminJson<{ deleted: number }>("/api/admin/research/uploads/bulk-delete", {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ items }),
	});
	return data.deleted;
}
