export type NigeriaUniversity = {
	id: string;
	label: string;
};

export type NigeriaUniversityGroup = {
	id: string;
	label: string;
	universities: NigeriaUniversity[];
};

export const NIGERIA_UNIVERSITY_GROUPS: NigeriaUniversityGroup[] = [
	{
		id: "federal",
		label: "Federal Universities",
		universities: [
			{ id: "unilag", label: "University of Lagos (UNILAG)" },
			{ id: "ui", label: "University of Ibadan (UI)" },
			{ id: "unn", label: "University of Nigeria, Nsukka (UNN)" },
			{ id: "oau", label: "Obafemi Awolowo University (OAU)" },
			{ id: "abu", label: "Ahmadu Bello University (ABU)" },
			{ id: "uniport", label: "University of Port Harcourt (UNIPORT)" },
			{ id: "uniben", label: "University of Benin (UNIBEN)" },
			{ id: "unical", label: "University of Calabar (UNICAL)" },
			{ id: "uniuyo", label: "University of Uyo (UNIUYO)" },
			{ id: "unimaid", label: "University of Maiduguri (UNIMAID)" },
			{ id: "unijos", label: "University of Jos (UNIJOS)" },
			{ id: "unilorin", label: "University of Ilorin (UNILORIN)" },
			{ id: "unizik", label: "Nnamdi Azikiwe University (UNIZIK)" },
			{ id: "futa", label: "Federal University of Technology, Akure (FUTA)" },
			{ id: "futminna", label: "Federal University of Technology, Minna (FUTMINNA)" },
			{ id: "futo", label: "Federal University of Technology, Owerri (FUTO)" },
			{ id: "fulafiya", label: "Federal University Lafia (FULAFIA)" },
			{ id: "fulokoja", label: "Federal University Lokoja (FULOKOJA)" },
			{ id: "fud", label: "Federal University Dutse (FUD)" },
			{ id: "fukashere", label: "Federal University Kashere (FUKASHERE)" },
			{ id: "funai", label: "Alex Ekwueme Federal University, Ndufu-Alike (FUNAI)" },
			{ id: "fugashua", label: "Federal University Gashua (FUGASHUA)" },
			{ id: "fugusau", label: "Federal University Gusau (FUGUSAU)" },
			{ id: "fuotuoke", label: "Federal University Otuoke (FUOTUOKE)" },
			{ id: "fupre", label: "Federal University Petroleum Resources, Effurun (FUPRE)" },
			{ id: "noun", label: "National Open University of Nigeria (NOUN)" },
			{ id: "nile", label: "Nigerian Defence Academy (NDA)" },
			{ id: "npa", label: "Nigerian Police Academy, Wudil" },
		],
	},
	{
		id: "state",
		label: "State Universities",
		universities: [
			{ id: "lasu", label: "Lagos State University (LASU)" },
			{ id: "delsu", label: "Delta State University (DELSU)" },
			{ id: "rsu", label: "Rivers State University (RSU)" },
			{ id: "imsu", label: "Imo State University (IMSU)" },
			{ id: "ebsu", label: "Ebonyi State University (EBSU)" },
			{ id: "enugu-state", label: "Enugu State University of Science & Technology (ESUT)" },
			{ id: "kogi-state", label: "Kogi State University (KSU)" },
			{ id: "kwasu", label: "Kwara State University (KWASU)" },
			{ id: "nasarawa-state", label: "Nasarawa State University (NSUK)" },
			{ id: "osun-state", label: "Osun State University (UNIOSUN)" },
			{ id: "plateau-state", label: "Plateau State University (PLASU)" },
			{ id: "uam", label: "University of Agriculture, Makurdi (UAM)" },
			{ id: "udusok", label: "Usmanu Danfodiyo University, Sokoto (UDUSOK)" },
			{ id: "taraba-state", label: "Taraba State University (TSU)" },
			{ id: "adekunle-ajasin", label: "Adekunle Ajasin University (AAUA)" },
			{ id: "ambrose-ali", label: "Ambrose Alli University (AAU Ekpoma)" },
			{ id: "chukwuemeka-odumegwu", label: "Chukwuemeka Odumegwu Ojukwu University (COOU)" },
			{ id: "cross-river", label: "Cross River University of Technology (CRUTECH)" },
			{ id: "kaduna-state", label: "Kaduna State University (KASU)" },
			{ id: "kano-state", label: "Kano University of Science & Technology (KUST)" },
		],
	},
	{
		id: "private",
		label: "Private Universities",
		universities: [
			{ id: "covenant", label: "Covenant University" },
			{ id: "babcock", label: "Babcock University" },
			{ id: "abuad", label: "Afe Babalola University (ABUAD)" },
			{ id: "bowen", label: "Bowen University" },
			{ id: "redeemer", label: "Redeemer's University" },
			{ id: "pan-atlantic", label: "Pan-Atlantic University" },
			{ id: "madonna", label: "Madonna University" },
			{ id: "crawford", label: "Crawford University" },
			{ id: "lead-city", label: "Lead City University" },
			{ id: "landmark", label: "Landmark University" },
			{ id: "american-univ-nigeria", label: "American University of Nigeria (AUN)" },
			{ id: "baze", label: "Baze University" },
			{ id: "veritas", label: "Veritas University" },
			{ id: "nile-univ", label: "Nile University of Nigeria" },
			{ id: "elizade", label: "Elizade University" },
			{ id: "achievers", label: "Achievers University" },
			{ id: "adeleke", label: "Adeleke University" },
			{ id: "al-hikmah", label: "Al-Hikmah University" },
			{ id: "anchor", label: "Anchor University" },
			{ id: "arthur-jarvis", label: "Arthur Jarvis University" },
			{ id: "augustine", label: "Augustine University" },
			{ id: "benson-idahosa-priv", label: "Benson Idahosa University" },
			{ id: "crescent", label: "Crescent University" },
			{ id: "edwin-clark", label: "Edwin Clark University" },
			{ id: "evangel", label: "Evangel University" },
			{ id: "fountain", label: "Fountain University" },
			{ id: "gregory", label: "Gregory University" },
			{ id: "hallmark", label: "Hallmark University" },
			{ id: "hezekiah", label: "Hezekiah University" },
			{ id: "igbinedion", label: "Igbinedion University" },
			{ id: "joseph-ayo", label: "Joseph Ayo Babalola University (JABU)" },
			{ id: "kings", label: "Kings University" },
			{ id: "michael-okpara", label: "Michael Okpara University of Agriculture (MOUAU)" },
			{ id: "novena", label: "Novena University" },
			{ id: "paul", label: "Paul University" },
			{ id: "precious-cornerstone", label: "Precious Cornerstone University" },
			{ id: "ritman", label: "Ritman University" },
			{ id: "salem-priv", label: "Salem University" },
			{ id: "summit", label: "Summit University" },
			{ id: "trinity", label: "Trinity University" },
			{ id: "wellspring", label: "Wellspring University" },
			{ id: "wesley", label: "Wesley University" },
			{ id: "western-delta", label: "Western Delta University" },
		],
	},
	{
		id: "polytechnic",
		label: "Polytechnics & Monotechnics",
		universities: [
			{ id: "yabatech", label: "Yaba College of Technology (YABATECH)" },
			{ id: "polyibadan", label: "The Polytechnic, Ibadan" },
			{ id: "polykaduna", label: "Kaduna Polytechnic" },
			{ id: "polybauchi", label: "Abubakar Tafawa Balewa University Polytechnic" },
			{ id: "polyakure", label: "Federal Polytechnic, Akure" },
			{ id: "polyilaro", label: "Federal Polytechnic, Ilaro" },
			{ id: "polynasarawa", label: "Federal Polytechnic, Nasarawa" },
			{ id: "polynekede", label: "Federal Polytechnic, Nekede" },
			{ id: "polyoffa", label: "Federal Polytechnic, Offa" },
			{ id: "polybida", label: "Federal Polytechnic, Bida" },
			{ id: "polyede", label: "Federal Polytechnic, Ede" },
			{ id: "polyowerri", label: "Federal Polytechnic, Owerri" },
			{ id: "polybauchi-fed", label: "Federal Polytechnic, Bauchi" },
			{ id: "polykaura", label: "Kaura Namoda Polytechnic" },
			{ id: "polywoji", label: "Port Harcourt Polytechnic" },
			{ id: "polyimo", label: "Imo State Polytechnic" },
			{ id: "polyosun", label: "Osun State Polytechnic" },
		],
	},
];

export const NIGERIA_UNIVERSITIES: NigeriaUniversity[] = NIGERIA_UNIVERSITY_GROUPS.flatMap(
	(group) => group.universities,
);

export function getUniversityLabel(id: string): string {
	return NIGERIA_UNIVERSITIES.find((u) => u.id === id)?.label ?? id;
}
